# Generated by Django 3.2.6 on 2022-07-02 22:04

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('copete', models.CharField(max_length=500)),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes')),
                ('imagen_epigrafe', models.CharField(blank=True, max_length=50, null=True)),
                ('habilitada', models.BooleanField(default=False)),
                ('votos', models.IntegerField(default=0)),
                ('puntaje', models.IntegerField(default=0)),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'pagina',
                'verbose_name_plural': 'paginas',
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('habilitada', models.BooleanField(default=False)),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'seccion',
                'verbose_name_plural': 'secciones',
            },
        ),
    ]
