# Generated by Django 4.0.4 on 2022-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='perfilid',
            field=models.IntegerField(default=0),
        ),
    ]
